version: '3.9'
services:
  db-container:
    image: postgres
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ptoor"]
      interval: 5s
      retries: 10
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: htmxnotes
      POSTGRES_TZ: Europe/Bucharest
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql